language: node_js
node_js:
  - "stable"
  -  "8"
  -  "8.2.1"
services:
  -  mongodb
before_install:
  - npm i -g npm@5.3.0
cache:
  directories:
    -  "node_modules"
env:
  - NODE_ENV=production PORT=8080
